# Контроллер состояния суставов (публикует /joint_states)
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Контроллеры скорости для каждого колеса
wheel_joint_fl_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_joint_fl
  pid: {p: 100.0, i: 0.01, d: 10.0}

wheel_joint_fr_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_joint_fr
  pid: {p: 100.0, i: 0.01, d: 10.0}

wheel_joint_bl_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_joint_bl
  pid: {p: 100.0, i: 0.01, d: 10.0}

wheel_joint_br_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_joint_br
  pid: {p: 100.0, i: 0.01, d: 10.0}